knp_paginator:
    page_range: 5                      # Number of page links to show
    default_options:
        page_name: page                # Query parameter name
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'
