# Custom admin routes - loaded before EasyAdmin to ensure priority
admin_user:
    resource: ../src/Controller/Admin/AdminUserController.php
    type: attribute
    prefix: /admin

admin_dashboard:
    resource: ../src/Controller/Admin/AdminDashboardController.php
    type: attribute
    prefix: /admin

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
        app_article_show:
            path: /article/{id}
            controller: App\Controller\ProjetController::show
    type: attribute
