controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
        app_article_show:
            path: /article/{id}
            controller: App\Controller\ProjetController::show
    type: attribute
